Remove highDynamicRange canvas setting
WICG/canvas-color-space pull request #45
Opened 2021-02-23 01:44 UTC by ccameron-chromium

Remove highDynamicRange setting from CanvasRenderingContext2DSettings and WebGLContextAttributes.

Enabling/disabling HDR will be done on the HTMLCanvasElement. Add language indicating this when discussing value clamping.

2021-02-23 01:46 UTC, ccameron-chromium commented
This largely-reverts the HDR parameter added earlier (it's not a complete revert, because it keeps the language related to value clamping).

Based on the W3C calls and related discussions, the HTMLCanvasElement is the right place to enable or disable HDR, and to specify HDR metadata. I'm leaving the addition of that API to a separate pull, so it can be scrutinized on its own.

2021-02-23 22:05 UTC, jdashg requested changes
I'm pretty confident hdr settings should be in the same struct as colorspace settings.

2021-02-23 22:15 UTC, jdashg commented
TBH <canvas> is just a div/iframe for generated graphics, similar to an <img> or <video>, where its source (rendering context) is really what determines its stats, not really the element itself normally.
I'm not sure what the plan is for images/videos for hdr but I would be surprised if the expected path is to both have to set the src and also tweak other params on the elements themselves. I would expect it to be as easy as `src="hdr.webm"`!

2021-02-24 05:48 UTC, kenrussell approved these changes
LGTM - would like to see where the HDR control is added to the canvas spec.

2021-02-25 05:38 UTC, ccameron-chromium commented
Merging this, based on our discussion on Tuesday.

2021-02-25 05:38 UTC, merged